### PR TITLE
fix support for flutter 2.29.0 

### PR DESCRIPTION
**Pull request by mufassalhussain**
After Upgrading to latest stable release of flutter 3.29.0, facing error as below:

**C:\Users\XTREME\AppData\Local\Pub\Cache\hosted\pub.dev\open_filex-4.6.0\android\src\main\java\com\crazecoder\openfile\OpenFilePlugin.java:73: error: cannot find symbol
public static void registerWith(PluginRegistry.Registrar registrar) {
^
symbol: class Registrar
location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':open_filex:compileDebugJavaWithJavac'.

### CODE REVIEW

**Comment by mufassalhussain** [comment]
I have fixed the issue, you can use the following as an alternative until release;

open_filex:
    git: 
      url: https://github.com/mufassalhussain/open_filex

**Comment by FeuerSoftwareMoritz** [comment]
Please correct PR title to "Fix support for flutter 3.29.0"

**Comment by mufassalhussain** [comment]
check now

**Comment by x3rud** [comment]
When will this fix be merged?

**Review by 0niel — APPROVED** [review]

**Comment by berke-ugur-openmind** [comment]
> I have fixed the issue, you can use the following as an alternative until release;
> 
> open_filex: git: url: https://github.com/mufassalhussain/open_filex

Thank you so much, it worked for me.

**Comment by GugaLincon** [comment]
Thank you.

**Comment by iamageo** [comment]
please, merge this! 🙏🏼

**Comment by TuyulTronik** [comment]
still_waiting

**Comment by DarenF-20C** [comment]
Is it possible to have it release soon?

**Comment by DarenF-20C** [comment]
@javaherisaber , FYI, blocking Android build with Flutter 3.29.0

**Comment by oscarshaitan** [comment]
> I have fixed the issue, you can use the following as an alternative until release;
> 
> open_filex: git: url: https://github.com/mufassalhussain/open_filex

Im usign this but  openfilex is not opening anything in prod, with the proguard rules on. If I turn off the rueles everythign works 
when the rules are one I got the error
` PlatformException(error, Attempt to read from field 'long android.content.res.XmlBlock$Parser.mParseState' on a null object reference in method 'int android.content.res.XmlBlock$Parser.getAttributeListValue(java.lang.String, java.lang.String, java.lang.String[], int)', null, java.lang.NullPointerException: Attempt to read from field 'long android.content.res.XmlBlock$Parser.mParseState' on a null object reference in method 'int android.content.res.XmlBlock$Parser.getAttributeListValue(java.lang.String, java.lang.String, java.lang.String[], int)'
`

I spend 2 days, tryign to sort out this problem with no results so far any ideas?

**Comment by jainmohit2001** [comment]
Any updates here?

**Comment by lucavenir** [comment]
hello is anyone there? @javaherisaber

**Comment by javaherisaber** [comment]
I'm working on the fix and will ship a new version

**Comment by oscarshaitan** [comment]
be aware that proguard is somehow striping some files too. just remember that

**Review by javaherisaber — APPROVED** [review]
